language: python
python: 
  - "3.6"
  - "3.7-dev"

install:
- pip install requests
- pip install pyre-check
- pip install pytest-cov

script:
- python3 -m pytest --cov-report term-missing --cov=gitlab_attendant
- pyre --source-directory . check